export const CHANGE_LOADING = 'CHANGE_LOADING' // 改变loading
export const CHANGE_SWITCH = 'CHANGE_SWITCH' // 改变switch
export const CHANGE_TITLE = 'CHANGE_TITLE' // 改变title
export const GET_HOT = 'GET_HOT' // 储存hot数据
export const GET_LOCATE = 'GET_LOCATE' // 获取当前城市
export const GET_CITIES = 'GET_CITIES' // 获取当前城市
export const GET_WISH = 'GET_WISH' // 储存待映最受欢迎
export const GET_COMING = 'GET_COMING' // 储存待映第一屏
export const GET_COMING_MORE = 'GET_COMING_MORE' // 储存待映更多
export const GET_HOT_SEARCH = 'GET_HOT_SEARCH' // 获取热门搜索
export const RECENT_CITIES = 'RECENT_CITIES' // 获取热门搜索
export const SEARCH_KEYWORD = 'SEARCH_KEYWORD' // 搜索关键词结果
export const CHANGE_MOVIEID = 'CHANGE_MOVIEID' // 电影id
export const UPDATE_LOCATE = 'UPDATE_LOCATE' // 更新本地信息
export const UPDATE_HOT_PAGEING = 'UPDATE_HOT_PAGEING' // 更新hot paging信息
export const UPDATE_COMING_PAGEING = 'UPDATE_COMING_PAGEING' // 更新coming paging信息
